server:
  port: 8081

spring:
  application:
    name: vehicle-catalog-emprescar

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: postgres
    password: root

  flyway:
    enabled: true
    locations: classpath:db/migration

  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus